### ISSUE TITLE
Could this be used to do a JSON dump of different content management APIs (wordpress, ghost)

### ISSUE THREAD

**Issue by balupton** [DataFire/DataFire#14]
for the purpose of taking that JSON dump and rendering it with a static site generator?

**Comment by bobby-brennan** [comment]
Yup, that sounds pretty reasonable.  This framework is meant to help build and manage any script/pipeline that relies on API/database connections.

Unfortunately we don't already have integrations for Ghost or Wordpress but they're not hard to build - you'd just need to create an OpenAPI spec.

**Comment by balupton** [comment]
Okay thanks. I'll go away and think about this. Cheers.

**Comment by easaw** [comment]
Dear @bobby-brennan 
Any good starting points for a new user to create an integration with WP for DataFire? Or more specifically, WooCommerce (which already has an API built in).

Any pointers appreciated 😃

**Comment by bobby-brennan** [comment]
Hi there,

I've just found [this project](https://github.com/starfishmod/WPAPI-SwaggerGenerator), which creates an Open API (aka Swagger) document from your WordPress install. You can use that Open API document to automatically generate a [custom DataFire integration](https://github.com/DataFire/DataFire/blob/master/docs/Integrations.md#add-integrations-by-url)

Hope that helps, let me know if you have any trouble!

-Bobby
