### ISSUE TITLE
HelloWorld example

### ISSUE THREAD

**Issue by datenwort** [DataFire/DataFire#21]
Hi,

I tried to follow the hello world example, but I got some problems with it. 

```javascript
module.exports = new datafire.Action({
  handler: (input, context) => {
    if (input.name === 'Voldemort') {
      return new datafire.Response({
        statusCode: 401,
        headers: {'Content-Type': 'text/html'},
        body: "<h1>Nope.</h1>",
      });
    } else {
      return {context, input};
    }
  }
})
```

In this example the input is always empty. If I check the output, I got the following result.

```javascript
{
  "context": {
    "results": {},
    "type": "http",
    "accounts": {},
    "startTime": "2017-06-08T08:20:04.600Z",
    "request": {
      "query": {
        "name": "world"
      },
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.49.1",
        "accept": "*/*"
      },
      "body": {},
      "path": "/hello",
      "method": "GET"
    }
  },
  "input": {}
}
```

node: v6.10.3
npm: 5.0.3
datafire: v2.2.0

**Comment by datenwort** [comment]
If I add 

```javascript
    inputs: [
        {
            title: 'name',
            type: 'string',
            maxLength: 20,
            default: 'World'
        }
    ]
```
to the file, I got the expected behaviour. So is it not possible to use it without JSON Schema?

**Comment by bobby-brennan** [comment]
Hi, thanks for pointing this out. I updated the documentation to include the "name" input.

You do need to declare inputs if you're going to use them with HTTP, though if `inputs` and `inputSchema` are undefined, you can pass arbitrary input when running actions in JavaScript or on the command line.

**Comment by datenwort** [comment]
Thx.
