### ISSUE TITLE
integrate glitch with petstore

### ISSUE THREAD

**Issue by coderofsalvation** [DataFire/DataFire#22]
* how does the integrate flag work? 
* how does one get generated api docs (i noticed swagger-middleware as dependency in package.json), and what's the url?

```
[sqz@localhost/tmp]  $ node -v
v6.9.1
[sqz@localhost/tmp]  $ datafire integrate --openapi http://petstore.swagger.io/v2/swagger.json
Created integration petstore_swagger in ./integrations/petstore_swagger
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at callback (/tmp/node_modules/datafire/src/commands/integrate.js:55:33)
    at fs.writeFile.e (/tmp/node_modules/datafire/src/commands/integrate.js:90:11)
    at /tmp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by bobby-brennan** [comment]
You just need the `--name` flag. I've just pushed a patch that marks this flag as required for the `integrate` command.

For example,
```bash
datafire integrate --openapi http://petstore.swagger.io/v2/swagger.json --name petstore
```

The `integrate` command just downloads the Open API spec to a local file, and creates a small `index.js` that initializes the integration from this file.

**Comment by bobby-brennan** [comment]
For Open API docs, it won't serve SwaggerUI, but you can access an Open API spec for your DataFire API at `/openapi.json`.  Just added a [note to the Cookbook](https://github.com/DataFire/DataFire/blob/master/docs/Cookbook.md#open-api)
