### ISSUE TITLE
Custom Integration is hidden (CSS) on the integrations page

### ISSUE THREAD

**Issue by easaw** [DataFire/DataFire#30]
Hi,

The link #CustomIntegrationModal seems to be hidden on the Integrations page. it appears for a half a second (see image) but is hidden with CSS. I changed the CSS to:
```
[hidden] {
    display: inline-block;
}
```
and the modal popped up - I assume we are not supposed to be using it at this time? (as it is clearly intentionally hidden)

![customintegration-screenshot](https://user-images.githubusercontent.com/17411112/35176359-6c9629cc-fd70-11e7-97c4-aebedb93c1ab.jpg)

_Update: NB: I want to have a try at adding WooCommerce API._

**Comment by bobby-brennan** [comment]
Thanks for the report - that link actually shouldn't be there. However, you can add a custom integration if create a new project and go to Integrations -> Available.

I'll make a note to fix this in the Web UI project and close this here.

For WooCommerce, you can [see this issue](https://github.com/DataFire/DataFire/issues/14) for info about creating an Open API definition from your WordPress/WooCommerce installation. Once you have the Open API definition, you'll be able to link to it in the custom integration modal.

**Comment by easaw** [comment]
Apologies, I think I created a misunderstanding. It is already hidden. However it appears for about 0.5secs (or less) before the page loads fully and you don't see it anymore. 

The code I mentioned is what I changed it too, using Chrome's DevTools.

The code at present is probably already sufficient and reads this:
```
[hidden] {
    display: hidden;
}
```

Thank you for the integration info :)
