### ISSUE TITLE
Error: Cannot find module '../distribution/cmd' ￼ ￼

### ISSUE THREAD

**Issue by alokissunny** [DataFire/DataFire#34]
this code in file bin/datafire 
#!/usr/bin/env node
if (process.version > 'v6') {
  module.exports = require('../src/cmd');
} else {
  module.exports = require('../distribution/cmd');
}

if process.version = v10 
then v10 > v6 gives false . We need to fix it.

**Comment by bobby-brennan** [comment]
Thanks for the report! This was fixed in v2.21.1
