### ISSUE TITLE
How to debug DataFire Actions?

### ISSUE THREAD

**Issue by vdurante** [DataFire/DataFire#35]
I know this question will sound stupid, but I am developing a DataFire.Action using VSCode. How do I properly debug the handler? Thanks in advance.

**Comment by bobby-brennan** [comment]
What exactly are you trying to debug? I'm not familiar with VSCode, but a good old `console.log` inside of the handler should work.

**Comment by vdurante** [comment]
I am trying to debug the execution of the handler. I know how to run it through command line, but using VSCODE (or any other IDE), I am able to debug step by step.

I found a "solution". I implemented a main that imports the action and calls the handler as `myaction.handler()`

**Comment by bobby-brennan** [comment]
OK cool. FYI you can also use `action.run(input, context)`, which will validate input and do some error handling.


You can absolutely chain actions together. If you're using [async/await](https://javascript.info/async-await), that might look something like this:

```js
const getHubspotAccounts = require('./get-hubspot-accounts');
const addAccountToDB = require('./add-account-to-db');
const datafire = require('datafire');

module.exports = new datafire.Action({
  handler: async (input, context) => {
    let accounts = await getHubspotAccounts.run({}, context);
    for (let account of accounts) {
      await addAccountToDB.run(account, context);
    }
    return `Added ${accounts.length} accounts`;
  }
})
```

**Comment by vdurante** [comment]
Thank you!
