### ISSUE TITLE
An API for DataFire itself

### ISSUE THREAD

**Issue by mattpardee** [DataFire/DataFire#46]
Is there an API for DataFire itself so CRUD operations can be performed against integrations, actions, triggers, etc? I know there's DataFire.io but say I wanted to manage these points with another interface, is there an established way of doing that?

Hopefully I didn't miss this somewhere obvious. Thanks!

**Comment by bobby-brennan** [comment]
Thanks for reaching out! Unfortunately though, there's no REST interface for DataFire - the CLI is your best bet.
